const traitsList = [
	{
		id: '66f609de-82c4-46d3-bc98-f2cfa55b2e75',
		category: 'Head',
		trait_name: 'Space Helmet',
		desired_rarity: 'Common',
		image_path: '/images/dummy_dog.png',
		thumb_image_path: 'Head/THM_Head_Mythic_SpaceHelmet.jpg',
		rarity: 0.1,
		rank: 2,
		dependencies: null,
	},
	{
		id: 'db064e21-79a0-4a35-947d-d8ad2cc68978k',
		category: 'Background',
		trait_name: "Harambe's Halo",
		desired_rarity: 'Cool',
		image_path: '/images/dummy_dog.png',
		thumb_image_path: 'Head/THM_Head_Mythic_HarambesHalo.jpg',
		rarity: 0.11,
		rank: 2,
		dependencies: null,
	},
	{
		id: '7cdf7bc7-9ef2-4074-b7af-8a725c3b6decj',
		category: 'Breed',
		trait_name: 'Prince Charming',
		desired_rarity: 'Groovy',
		image_path: '/images/dummy_dog.png',
		thumb_image_path: 'Clothing/THM_Clothing_Mythic_PrinceCharming.jpg',
		rarity: 0.12,
		rank: 2,
		dependencies: null,
	},
	{
		id: '894444c7-b75a-46b8-8d45-8453b265951i',
		category: 'Clothes',
		trait_name: 'Acid Trip',
		desired_rarity: 'Fly',
		image_path: '/images/dummy_dog.png',
		thumb_image_path: 'FurSkin/THM_FurSkin_Mythic_AcidTrip.jpg',
		rarity: 0.13,
		rank: 2,
		dependencies: null,
	}
	,
	{
		id: '894444c7-b75a-46b8-8d45-8453b265951h',
		category: 'eyes',
		trait_name: 'Acid Trip',
		desired_rarity: 'Dynomite',
		image_path: '/images/dummy_dog.png',
		thumb_image_path: 'FurSkin/THM_FurSkin_Mythic_AcidTrip.jpg',
		rarity: 0.13,
		rank: 2,
		dependencies: null,
	},
	{
		id: '66f609de-82c4-46d3-bc98-f2cfa55b2e75g',
		category: 'Head',
		trait_name: 'Space Helmet',
		desired_rarity: 'Common',
		image_path: '/images/dummy_dog.png',
		thumb_image_path: 'Head/THM_Head_Mythic_SpaceHelmet.jpg',
		rarity: 0.1,
		rank: 2,
		dependencies: null,
	},
	{
		id: 'db064e21-79a0-4a35-947d-d8ad2cc68978f',
		category: 'Background',
		trait_name: "Harambe's Halo",
		desired_rarity: 'Cool',
		image_path: '/images/dummy_dog.png',
		thumb_image_path: 'Head/THM_Head_Mythic_HarambesHalo.jpg',
		rarity: 0.11,
		rank: 2,
		dependencies: null,
	},
	{
		id: '7cdf7bc7-9ef2-4074-b7af-8a725c3b6dee',
		category: 'Breed',
		trait_name: 'Prince Charming',
		desired_rarity: 'Groovy',
		image_path: '/images/dummy_dog.png',
		thumb_image_path: 'Clothing/THM_Clothing_Mythic_PrinceCharming.jpg',
		rarity: 0.12,
		rank: 2,
		dependencies: null,
	},
	{
		id: '894444c7-b75a-46b8-8d45-8453b265951d',
		category: 'Clothes',
		trait_name: 'Acid Trip',
		desired_rarity: 'Fly',
		image_path: '/images/dummy_dog.png',
		thumb_image_path: 'FurSkin/THM_FurSkin_Mythic_AcidTrip.jpg',
		rarity: 0.13,
		rank: 2,
		dependencies: null,
	}
	,
	{
		id: '894444c7-b75a-46b8-8d45-8453b265951c',
		category: 'eyes',
		trait_name: 'Acid Trip',
		desired_rarity: 'Dynomite',
		image_path: '/images/dummy_dog.png',
		thumb_image_path: 'FurSkin/THM_FurSkin_Mythic_AcidTrip.jpg',
		rarity: 0.13,
		rank: 2,
		dependencies: null,
	}
]

export default JSON.stringify(traitsList)